name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@ef7231f5cbdbf2c626902ff7ff771f3add58665b
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: playground-site
          build-command: yarn build-playground
