name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@4188b26312f276decb1a6ef6fc09b7030f7da291
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: playground-site
          build-command: yarn build-playground
